# Generated by Django 5.2.15 on 2026-07-03 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProfileAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_snapshot_hash', models.CharField(db_index=True, max_length=64)),
                ('assessment_version', models.CharField(default='2026-07-profile-v1', max_length=40)),
                ('model_provider', models.CharField(blank=True, max_length=40)),
                ('model_name', models.CharField(blank=True, max_length=120)),
                ('raw_input_summary_json', models.JSONField(blank=True, default=dict)),
                ('raw_output_json', models.JSONField(blank=True, default=dict)),
                ('overall_profile_score', models.PositiveSmallIntegerField()),
                ('profile_evidence_score', models.PositiveSmallIntegerField()),
                ('activities_score', models.PositiveSmallIntegerField()),
                ('honors_olympiads_score', models.PositiveSmallIntegerField()),
                ('research_experience_score', models.PositiveSmallIntegerField()),
                ('portfolio_score', models.PositiveSmallIntegerField()),
                ('subject_passion_score', models.PositiveSmallIntegerField()),
                ('curiosity_score', models.PositiveSmallIntegerField()),
                ('originality_score', models.PositiveSmallIntegerField()),
                ('leadership_score', models.PositiveSmallIntegerField()),
                ('community_impact_score', models.PositiveSmallIntegerField()),
                ('research_fit_score', models.PositiveSmallIntegerField()),
                ('olympiads_score', models.PositiveSmallIntegerField()),
                ('confidence', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_index=True, default='low', max_length=12)),
                ('public_summary', models.TextField(blank=True)),
                ('evidence_used', models.JSONField(blank=True, default=list)),
                ('missing_data', models.JSONField(blank=True, default=list)),
                ('improvement_areas', models.JSONField(blank=True, default=list)),
                ('internal_keywords', models.JSONField(blank=True, default=list)),
                ('category_rationales', models.JSONField(blank=True, default=dict)),
                ('target_context_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('is_stale', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', '-created_at'], name='profile_ass_user_id_cd476d_idx'), models.Index(fields=['user', 'profile_snapshot_hash', 'is_stale'], name='profile_ass_user_id_0e8eae_idx')],
            },
        ),
    ]
