# Generated by Django 5.2.16 on 2026-07-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile_assessment_service", "0002_aiprofileassessment_benchmark_academic_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiprofileassessment",
            name="qualitative_fit_scores",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
