# Generated by Django 5.2.16 on 2026-07-15 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import services.telegram_service.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramLinkToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=services.telegram_service.models._generate_link_token, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(default=services.telegram_service.models._default_token_expiry)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_link_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReminderDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('telegram', 'Telegram')], max_length=20)),
                ('related_entity_type', models.CharField(max_length=40)),
                ('related_entity_id', models.PositiveIntegerField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'channel', 'related_entity_type', 'related_entity_id'), name='unique_reminder_per_entity_per_channel')],
            },
        ),
        migrations.CreateModel(
            name='TelegramLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(db_index=True)),
                ('telegram_username', models.CharField(blank=True, max_length=64)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('unlinked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_link', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('unlinked_at__isnull', True)), fields=('telegram_user_id',), name='unique_active_telegram_user_id')],
            },
        ),
    ]
