# Generated by Django 5.2.15 on 2026-07-02 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_service', '0002_applicationmilestone_notes_and_more'),
        ('essay_service', '0001_initial'),
        ('university_service', '0009_university_cost_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='essayworkspace',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='essay_workspaces', to='application_service.applicationtrackeritem'),
        ),
        migrations.AddField(
            model_name='essayworkspace',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='essayworkspace',
            name='notes',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='essayworkspace',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='essayworkspace',
            name='prompt_confidence',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=12),
        ),
        migrations.AddField(
            model_name='essayworkspace',
            name='prompt_verification_status',
            field=models.CharField(choices=[('verified', 'Verified'), ('needs_verification', 'Needs verification'), ('missing', 'Missing')], default='missing', max_length=24),
        ),
        migrations.AddField(
            model_name='essayworkspace',
            name='suggestion_key',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='essayworkspace',
            name='status',
            field=models.CharField(choices=[('suggested', 'Suggested'), ('planned', 'Planned'), ('not_started', 'Not started'), ('drafting', 'Drafting'), ('needs_revision', 'Needs revision'), ('reviewed', 'Reviewed'), ('ready', 'Ready'), ('submitted', 'Submitted'), ('skipped', 'Skipped')], default='not_started', max_length=20),
        ),
        migrations.AddIndex(
            model_name='essayworkspace',
            index=models.Index(fields=['user', 'priority'], name='essay_servi_user_id_a4e8d7_idx'),
        ),
        migrations.AddConstraint(
            model_name='essayworkspace',
            constraint=models.UniqueConstraint(condition=models.Q(('suggestion_key', ''), _negated=True), fields=('user', 'suggestion_key'), name='unique_essay_suggestion_per_user'),
        ),
    ]
