# Generated by Django 5.2.15 on 2026-07-03 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_service', '0002_applicationmilestone_notes_and_more'),
        ('essay_service', '0002_essayworkspace_application_essayworkspace_due_date_and_more'),
        ('university_service', '0010_universitysubjectranking_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIEssayScoreReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('essay_text_hash', models.CharField(db_index=True, max_length=64)),
                ('context_hash', models.CharField(db_index=True, max_length=64)),
                ('rubric_version', models.CharField(default='essay_numeric_v1', max_length=50)),
                ('model_provider', models.CharField(default='gemini', max_length=50)),
                ('model_name', models.CharField(max_length=100)),
                ('raw_output_json', models.JSONField(default=dict)),
                ('overall_essay_readiness', models.PositiveSmallIntegerField()),
                ('prompt_fit', models.PositiveSmallIntegerField()),
                ('structure', models.PositiveSmallIntegerField()),
                ('specificity_evidence', models.PositiveSmallIntegerField()),
                ('authenticity', models.PositiveSmallIntegerField()),
                ('language_clarity', models.PositiveSmallIntegerField()),
                ('word_limit_discipline', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('school_program_alignment', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('confidence', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('verified_context_used', models.BooleanField(default=False)),
                ('word_count', models.PositiveIntegerField()),
                ('word_limit_status', models.CharField(choices=[('under', 'Under'), ('within', 'Within'), ('near_limit', 'Near limit'), ('over', 'Over'), ('unknown', 'Unknown')], max_length=20)),
                ('ai_paraphrase_style_signal', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('inconclusive', 'Inconclusive')], max_length=20)),
                ('generic_language_signal', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('unsupported_claims_signal', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('inconclusive', 'Inconclusive')], max_length=20)),
                ('strength_flags', models.JSONField(blank=True, default=list)),
                ('risk_flags', models.JSONField(blank=True, default=list)),
                ('approximate_suggestions', models.JSONField(blank=True, default=list)),
                ('source_warnings', models.JSONField(blank=True, default=list)),
                ('disclaimers', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_essay_score_reports', to='application_service.applicationtrackeritem')),
                ('essay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_score_reports', to='essay_service.essayworkspace')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_essay_score_reports', to='university_service.universityprogram')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_essay_score_reports', to='university_service.university')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_essay_score_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['essay', 'essay_text_hash', 'context_hash'], name='essay_servi_essay_i_74ccf8_idx'), models.Index(fields=['user', 'created_at'], name='essay_servi_user_id_09d12f_idx')],
            },
        ),
    ]
