# Generated by Django 5.2.16 on 2026-07-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essay_service', '0003_aiessayscorereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiessayscorereport',
            name='action_plan',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='aiessayscorereport',
            name='biggest_strength',
            field=models.CharField(blank=True, max_length=280),
        ),
        migrations.AddField(
            model_name='aiessayscorereport',
            name='biggest_weakness',
            field=models.CharField(blank=True, max_length=280),
        ),
        migrations.AddField(
            model_name='aiessayscorereport',
            name='reflective_questions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
