# Generated by Django 5.2.15 on 2026-06-22 09:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Free'), ('starter', '$5'), ('growth', '$10'), ('premium', '$25')], max_length=20, unique=True)),
                ('ai_messages_per_month', models.PositiveIntegerField(default=5)),
                ('essay_reviews_per_month', models.PositiveIntegerField(default=1)),
                ('saved_events', models.PositiveIntegerField(default=25)),
                ('feature_flags', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Free'), ('starter', '$5'), ('growth', '$10'), ('premium', '$25')], db_index=True, default='free', max_length=20)),
                ('period_started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ai_message_count', models.PositiveIntegerField(default=0)),
                ('essay_review_count', models.PositiveIntegerField(default=0)),
                ('saved_events_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ai_message', 'AI message'), ('essay_review', 'Essay review'), ('saved_event', 'Saved event')], db_index=True, max_length=30)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
