# Generated by Django 5.2.16 on 2026-07-10 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_service', '0002_applicationmilestone_notes_and_more'),
        ('user_profile_service', '0008_studentprofile_a_level_subjects_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtrackeritem',
            name='fit_tier',
            field=models.CharField(choices=[('reach', 'Reach'), ('competitive', 'Competitive'), ('target', 'Target'), ('safety', 'Safer'), ('unknown', 'Not yet estimated')], default='unknown', max_length=15),
        ),
        migrations.AddField(
            model_name='applicationtrackeritem',
            name='source',
            field=models.CharField(choices=[('user_added', 'Added by student'), ('roadmap', 'Roadmap'), ('recommendation', 'Recommendation'), ('imported', 'Imported')], default='user_added', max_length=20),
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('transcript', 'Transcript'), ('passport', 'Passport'), ('certificate', 'Certificate'), ('test_report', 'Test report'), ('portfolio', 'Portfolio'), ('financial_document', 'Financial document'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=240)),
                ('status', models.CharField(choices=[('missing', 'Missing'), ('uploaded', 'Uploaded'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='missing', max_length=20)),
                ('notes', models.TextField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='application_service.applicationtrackeritem')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['application', 'status'], name='application_applica_5f5b4c_idx')],
            },
        ),
        migrations.CreateModel(
            name='ApplicationRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommender_name', models.CharField(blank=True, max_length=150)),
                ('recommender_role', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('not_requested', 'Not requested'), ('requested', 'Requested'), ('agreed', 'Agreed'), ('submitted', 'Submitted'), ('unavailable', 'Unavailable')], default='not_requested', max_length=20)),
                ('request_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_requests', to='application_service.applicationtrackeritem')),
                ('recommender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_requests', to='user_profile_service.recommender')),
            ],
            options={
                'ordering': ('due_date', '-created_at'),
                'indexes': [models.Index(fields=['application', 'status'], name='application_applica_a631d3_idx')],
            },
        ),
        migrations.CreateModel(
            name='ApplicationRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_type', models.CharField(choices=[('transcript', 'Transcript'), ('test_scores', 'Test scores'), ('english_proof', 'English proficiency proof'), ('essay', 'Essay'), ('supplement', 'Supplement'), ('recommendation', 'Recommendation'), ('portfolio', 'Portfolio'), ('financial_aid', 'Financial aid'), ('passport', 'Passport'), ('application_fee', 'Application fee'), ('interview', 'Interview'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('missing', 'Missing'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('waived', 'Waived'), ('not_required', 'Not required')], default='missing', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_required', models.BooleanField(default=True)),
                ('source', models.CharField(choices=[('university_data', 'University data'), ('user_created', 'Added by student'), ('system_generated', 'Generated checklist')], default='user_created', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='application_service.applicationtrackeritem')),
            ],
            options={
                'ordering': ('order', 'due_date', '-created_at'),
                'indexes': [models.Index(fields=['application', 'status'], name='application_applica_77d157_idx')],
            },
        ),
    ]
