# Generated by Django 5.2.16 on 2026-07-14 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_service', '0004_target_university_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtrackeritem',
            name='application_round',
            field=models.CharField(choices=[('early_decision', 'Early decision'), ('early_action', 'Early action'), ('restrictive_early_action', 'Restrictive early action'), ('single_choice_early_action', 'Single-choice early action'), ('regular_decision', 'Regular decision'), ('rolling', 'Rolling'), ('scholarship', 'Scholarship'), ('other', 'Other')], default='regular_decision', max_length=30),
        ),
    ]
