# Generated by Django 5.2.15 on 2026-06-22 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=180)),
                ('country', models.CharField(blank=True, db_index=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('grade', models.CharField(blank=True, max_length=50)),
                ('education_status', models.CharField(blank=True, max_length=120)),
                ('intended_major', models.CharField(blank=True, max_length=180)),
                ('target_countries', models.JSONField(blank=True, default=list)),
                ('target_universities', models.JSONField(blank=True, default=list)),
                ('scholarship_need', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('unsure', 'Not sure')], default='unsure', max_length=10)),
                ('sat_level', models.CharField(blank=True, max_length=100)),
                ('ielts_level', models.CharField(blank=True, max_length=100)),
                ('essay_level', models.CharField(blank=True, max_length=100)),
                ('onboarding_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interested_classes', models.JSONField(blank=True, default=list)),
                ('ap_interests', models.JSONField(blank=True, default=list)),
                ('activity_interests', models.JSONField(blank=True, default=list)),
                ('career_interests', models.JSONField(blank=True, default=list)),
                ('mun_debate_interest', models.BooleanField(default=False)),
                ('research_interest', models.BooleanField(default=False)),
                ('finance_literacy_interest', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
