# Generated by Django 5.2.15 on 2026-06-22 10:22

from django.db import migrations, models


def copy_legacy_profile_data(apps, schema_editor):
    StudentProfile = apps.get_model("user_profile_service", "StudentProfile")
    for profile in StudentProfile.objects.all().iterator():
        changed_fields = []
        if profile.intended_major and not profile.intended_majors:
            profile.intended_majors = [profile.intended_major]
            changed_fields.append("intended_majors")

        scores = dict(profile.test_scores or {})
        if profile.sat_level and "sat" not in scores:
            scores["sat"] = profile.sat_level
        if profile.ielts_level and "ielts" not in scores:
            scores["ielts"] = profile.ielts_level
        if scores != profile.test_scores:
            profile.test_scores = scores
            changed_fields.append("test_scores")

        if changed_fields:
            profile.save(update_fields=changed_fields)


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='intended_degree',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='intended_majors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='languages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='school_or_university',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=33),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='test_scores',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='interests',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(copy_legacy_profile_data, migrations.RunPython.noop),
    ]
