# Generated by Django 5.2.15 on 2026-06-23 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile_service', '0002_studentprofile_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='activities',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='essay_stage',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='essay_status',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('not_yet', 'Not yet')], default='not_yet', max_length=12),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='exam_plans',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='expected_graduation_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='gpa_scale',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='major_unsure',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='onboarding_sections',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='onboarding_version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='preparation_needs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='support_priorities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='university_unsure',
            field=models.BooleanField(default=False),
        ),
    ]
