# Generated by Django 5.2.15 on 2026-07-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile_service', '0007_alter_studentprofile_original_gpa_scale_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='a_level_subjects_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='annual_budget_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='annual_budget_currency',
            field=models.CharField(blank=True, default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='ap_courses_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='budget_flexibility',
            field=models.CharField(choices=[('strict', 'Strict'), ('flexible', 'Flexible'), ('unknown', 'Unknown')], default='unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='course_rigor_level',
            field=models.CharField(choices=[('standard', 'Standard'), ('advanced', 'Advanced'), ('highly_advanced', 'Highly advanced'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='honors_courses_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='ib_courses_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
