# Generated by Django 5.2.16 on 2026-07-17 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile_service', '0008_studentprofile_a_level_subjects_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='activity',
            name='impact_number',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='activity',
            name='organization',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='activity',
            name='role',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='beneficiaries',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='description',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='impact_number',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='organization',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='role',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
