# Generated by Django 5.2.16 on 2026-07-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile_service', '0011_userpreference_product_tour_dismissed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essaydraft',
            name='notes',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='honor',
            name='description',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='honor',
            name='issuing_organization',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='honor',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='description',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='description',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='users_impact',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='recommender',
            name='notes',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='description',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='research_question',
            field=models.TextField(blank=True, max_length=800),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sport',
            name='competition_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='sport',
            name='description',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='sport',
            name='peak_result',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='sport',
            name='sport_name',
            field=models.CharField(max_length=200),
        ),
    ]
