# Generated by Django 5.2.15 on 2026-06-22 09:23

import django.db.models.deletion
from django.db import migrations, models

import common.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('slug', models.SlugField(max_length=260, unique=True)),
                ('country', models.CharField(db_index=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('official_website', models.URLField(validators=[common.validators.validate_http_url])),
                ('summary', models.TextField(blank=True)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
                'indexes': [models.Index(fields=['country', 'is_published'], name='university__country_0ab128_idx')],
            },
        ),
        migrations.CreateModel(
            name='UniversityDataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_title', models.CharField(max_length=240)),
                ('source_url', models.URLField(validators=[common.validators.validate_http_url])),
                ('is_official', models.BooleanField(default=True)),
                ('published_at', models.DateField(blank=True, null=True)),
                ('retrieved_at', models.DateTimeField(auto_now_add=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='university_service.university')),
            ],
        ),
        migrations.CreateModel(
            name='UniversityProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('degree_level', models.CharField(blank=True, max_length=80)),
                ('official_url', models.URLField(blank=True, validators=[common.validators.validate_http_url])),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='university_service.university')),
            ],
        ),
        migrations.CreateModel(
            name='UniversityRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_type', models.CharField(db_index=True, max_length=100)),
                ('value', models.CharField(max_length=240)),
                ('notes', models.TextField(blank=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='university_service.university')),
            ],
        ),
        migrations.CreateModel(
            name='UniversityScholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('summary', models.TextField(blank=True)),
                ('official_url', models.URLField(validators=[common.validators.validate_http_url])),
                ('deadline', models.DateField(blank=True, null=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarships', to='university_service.university')),
            ],
        ),
    ]
