# Generated by Django 5.2.15 on 2026-06-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_service', '0004_university_international_office_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='ap_recommendations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='university',
            name='application_requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='university',
            name='data_quality_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='university',
            name='deadlines_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='university',
            name='financial_aid_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='university',
            name='ielts_competitive',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='scholarships_text',
            field=models.TextField(blank=True),
        ),
    ]
