# Generated by Django 5.2.16 on 2026-07-10 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_service', '0013_import_row_log_sheet_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityModerationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_review', 'Pending review'), ('verified', 'Verified'), ('needs_update', 'Needs update'), ('rejected', 'Rejected'), ('archived', 'Archived')], db_index=True, default='pending_review', max_length=20)),
                ('field_name', models.CharField(blank=True, max_length=100)),
                ('issue_type', models.CharField(choices=[('missing_source', 'Missing source'), ('outdated_data', 'Outdated data'), ('conflicting_data', 'Conflicting data'), ('shifted_row', 'Shifted row'), ('boilerplate', 'Boilerplate'), ('user_report', 'User report'), ('admin_note', 'Admin note')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='university_moderation_records_created', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='university_moderation_records_resolved', to=settings.AUTH_USER_MODEL)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_records', to='university_service.university')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['university', 'status'], name='university__univers_2315de_idx')],
            },
        ),
    ]
