# Generated by Django 5.2.16 on 2026-07-10 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_service', '0014_universitymoderationrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversitySemanticFit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_snapshot_hash', models.CharField(max_length=64)),
                ('university_updated_at', models.DateTimeField()),
                ('prompt_version', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('failed', 'Failed')], default='ok', max_length=10)),
                ('main_strength', models.CharField(blank=True, max_length=300)),
                ('main_risk', models.CharField(blank=True, max_length=300)),
                ('summary', models.CharField(blank=True, max_length=600)),
                ('next_actions', models.JSONField(blank=True, default=list)),
                ('model_provider', models.CharField(blank=True, max_length=40)),
                ('model_name', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semantic_fits', to='university_service.university')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semantic_fits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'university'), name='unique_semantic_fit_per_user_university')],
            },
        ),
    ]
