# Generated by Django 5.2.16 on 2026-07-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_service', '0015_universitysemanticfit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='gpa_average',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='gpa_average_scale',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
