# Generated by Django 5.2.15 on 2026-06-22 10:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import common.validators


def migrate_event_lifecycle(apps, schema_editor):
    Event = apps.get_model("event_service", "Event")
    EventModerationLog = apps.get_model("event_service", "EventModerationLog")
    status_map = {
        "pending": "pending_review",
        "approved": "published",
        "rejected": "archived",
    }
    for event in Event.objects.all().iterator():
        event.moderation_status = status_map.get(event.moderation_status, event.moderation_status)
        event.is_online = event.format in {"online", "hybrid"}
        event.price_type = "free" if event.is_free else "unknown"
        if not event.short_description:
            event.short_description = event.description[:360]
        event.save(
            update_fields=[
                "moderation_status",
                "is_online",
                "price_type",
                "short_description",
            ]
        )
    for log in EventModerationLog.objects.all().iterator():
        previous_status = status_map.get(log.previous_status, log.previous_status)
        new_status = status_map.get(log.new_status, log.new_status)
        changed_fields = []
        if previous_status != log.previous_status:
            log.previous_status = previous_status
            changed_fields.append("previous_status")
        if new_status != log.new_status:
            log.new_status = new_status
            changed_fields.append("new_status")
        if changed_fields:
            log.save(update_fields=changed_fields)


class Migration(migrations.Migration):

    dependencies = [
        ('event_service', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('cancelled', 'Cancelled'), ('waitlisted', 'Waitlisted'), ('attended', 'Attended')], db_index=True, default='registered', max_length=20)),
                ('registration_data', models.JSONField(blank=True, default=dict)),
                ('contact_snapshot', models.JSONField(blank=True, default=dict)),
                ('payment_status', models.CharField(choices=[('not_required', 'Not required'), ('pending', 'Pending'), ('paid', 'Paid'), ('waived', 'Waived')], db_index=True, default='not_required', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='event',
            name='cover_image_url',
            field=models.URLField(blank=True, validators=[common.validators.validate_http_url]),
        ),
        migrations.AddField(
            model_name='event',
            name='currency',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='event',
            name='is_online',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='online_url',
            field=models.URLField(blank=True, validators=[common.validators.validate_http_url]),
        ),
        migrations.AddField(
            model_name='event',
            name='price_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='price_type',
            field=models.CharField(choices=[('free', 'Free'), ('paid', 'Paid'), ('external', 'External payment'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='short_description',
            field=models.CharField(blank=True, max_length=360),
        ),
        migrations.AddField(
            model_name='event',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], db_index=True, default='public', max_length=20),
        ),
        migrations.RunPython(migrate_event_lifecycle, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='event',
            name='moderation_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('published', 'Published'), ('cancelled', 'Cancelled'), ('archived', 'Archived')], db_index=True, default='pending_review', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventmoderationlog',
            name='new_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('published', 'Published'), ('cancelled', 'Cancelled'), ('archived', 'Archived')], max_length=20),
        ),
        migrations.AlterField(
            model_name='eventmoderationlog',
            name='previous_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('published', 'Published'), ('cancelled', 'Cancelled'), ('archived', 'Archived')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['visibility', 'moderation_status', 'starts_at'], name='event_servi_visibil_87195f_idx'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='event_service.event'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['event', 'status'], name='event_servi_event_i_d071d2_idx'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['user', 'status'], name='event_servi_user_id_3edb5d_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('registered', 'waitlisted', 'attended'))), fields=('user', 'event'), name='unique_active_event_registration'),
        ),
    ]
