# Generated by Django 5.2.15 on 2026-06-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_service', '0002_eventregistration_event_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='moderation_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('published', 'Published'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('archived', 'Archived')], db_index=True, default='pending_review', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventmoderationlog',
            name='new_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('published', 'Published'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('archived', 'Archived')], max_length=20),
        ),
        migrations.AlterField(
            model_name='eventmoderationlog',
            name='previous_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('published', 'Published'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('archived', 'Archived')], max_length=20),
        ),
    ]
