# Generated by Django 5.2.15 on 2026-07-02 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_service', '0003_alter_event_moderation_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(choices=[('short_text', 'Short text'), ('long_text', 'Long text'), ('single_choice', 'Single choice'), ('multiple_choice', 'Multiple choice'), ('number', 'Number'), ('date', 'Date'), ('email', 'Email'), ('phone', 'Phone'), ('telegram', 'Telegram username'), ('url', 'File or link URL')], max_length=32)),
                ('label', models.CharField(max_length=160)),
                ('help_text', models.CharField(blank=True, max_length=500)),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('choices', models.JSONField(blank=True, default=list)),
                ('validation', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='event_service.event')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='EventNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('registration_confirmed', 'Registration confirmed'), ('registration_cancelled', 'Registration cancelled'), ('event_approved', 'Event approved'), ('event_rejected', 'Event rejected'), ('organizer_new_registration', 'New registration'), ('event_reminder_pending', 'Event reminder pending'), ('check_in_confirmed', 'Check-in confirmed'), ('participation_verified', 'Participation verified')], max_length=64)),
                ('channel', models.CharField(choices=[('internal', 'Internal'), ('telegram', 'Telegram')], default='internal', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_notifications_created', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='event_service.event')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_notifications', to=settings.AUTH_USER_MODEL)),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='event_service.eventregistration')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='EventRegistrationAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='event_service.eventformfield')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='event_service.eventregistration')),
            ],
            options={
                'ordering': ('field__order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='EventTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=96, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('checked_in', 'Checked in'), ('expired', 'Expired')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='event_service.event')),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='event_service.eventregistration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_status', models.CharField(choices=[('checked_in', 'Checked in'), ('no_show', 'No show')], default='checked_in', max_length=20)),
                ('participation_type', models.CharField(choices=[('attendee', 'Attendee'), ('speaker', 'Speaker'), ('volunteer', 'Volunteer')], default='attendee', max_length=20)),
                ('verification_status', models.CharField(choices=[('verified', 'Verified'), ('revoked', 'Revoked')], default='verified', max_length=20)),
                ('verified_at', models.DateTimeField()),
                ('record_id', models.UUIDField(unique=True)),
                ('public_verification_code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participation_records', to='event_service.event')),
                ('organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_participation_records', to=settings.AUTH_USER_MODEL)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='participation_record', to='event_service.eventregistration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participation_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-verified_at',),
            },
        ),
        migrations.AddIndex(
            model_name='eventformfield',
            index=models.Index(fields=['event', 'order'], name='event_servi_event_i_4ef15a_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventformfield',
            constraint=models.UniqueConstraint(fields=('event', 'order'), name='unique_event_form_field_order'),
        ),
        migrations.AddIndex(
            model_name='eventnotification',
            index=models.Index(fields=['recipient', 'status'], name='event_servi_recipie_39ff8b_idx'),
        ),
        migrations.AddIndex(
            model_name='eventnotification',
            index=models.Index(fields=['event', 'notification_type'], name='event_servi_event_i_489038_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventregistrationanswer',
            constraint=models.UniqueConstraint(fields=('registration', 'field'), name='unique_event_registration_answer'),
        ),
        migrations.AddIndex(
            model_name='eventticket',
            index=models.Index(fields=['event', 'status'], name='event_servi_event_i_042462_idx'),
        ),
        migrations.AddIndex(
            model_name='eventticket',
            index=models.Index(fields=['user', 'status'], name='event_servi_user_id_1db599_idx'),
        ),
        migrations.AddIndex(
            model_name='participationrecord',
            index=models.Index(fields=['user', 'verification_status'], name='event_servi_user_id_016fb0_idx'),
        ),
        migrations.AddIndex(
            model_name='participationrecord',
            index=models.Index(fields=['event', 'attendance_status'], name='event_servi_event_i_7ed0cb_idx'),
        ),
    ]
