# Generated by Django 5.2.16 on 2026-07-16 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('event_service', '0005_organizermoderation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('telegram_username', models.CharField(max_length=33)),
                ('description', models.TextField(max_length=1000)),
                ('project_link', models.URLField(blank=True, validators=[common.validators.validate_http_url])),
                ('motivation', models.TextField(max_length=500)),
                ('experience', models.TextField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizer_applications', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizer_application_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('applicant',), name='unique_pending_organizer_application_per_user')],
            },
        ),
    ]
