# Generated by Django 5.2.16 on 2026-07-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_service', '0006_organizerapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizerapplication',
            name='description',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='organizerapplication',
            name='experience',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organizerapplication',
            name='motivation',
            field=models.TextField(max_length=1000),
        ),
    ]
