# Generated by Django 5.2.16 on 2026-07-10 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('user_registered', 'User registered'), ('profile_updated', 'Profile updated'), ('profile_assessment_refreshed', 'Profile assessment refreshed'), ('university_viewed', 'University viewed'), ('university_shortlisted', 'University shortlisted'), ('application_created', 'Application created'), ('application_status_changed', 'Application status changed'), ('roadmap_generated', 'Roadmap generated'), ('roadmap_task_completed', 'Roadmap task completed'), ('essay_review_requested', 'Essay review requested'), ('event_registered', 'Event registered'), ('organizer_event_created', 'Organizer event created')], db_index=True, max_length=60)),
                ('entity_type', models.CharField(blank=True, max_length=40)),
                ('entity_id', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='activity_se_event_t_f249a9_idx'), models.Index(fields=['user', 'created_at'], name='activity_se_user_id_d568c2_idx')],
            },
        ),
    ]
