# Generated by Django 5.2.16 on 2026-07-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_service', '0003_alter_analyticsevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsevent',
            name='event_type',
            field=models.CharField(choices=[('user_registered', 'User registered'), ('profile_updated', 'Profile updated'), ('profile_assessment_refreshed', 'Profile assessment refreshed'), ('university_viewed', 'University viewed'), ('university_shortlisted', 'University shortlisted'), ('university_pinned', 'University pinned'), ('university_excluded', 'University excluded'), ('recommendation_impression', 'Recommendation impression'), ('onboarding_started', 'Onboarding started'), ('onboarding_completed', 'Onboarding completed'), ('application_created', 'Application created'), ('application_status_changed', 'Application status changed'), ('roadmap_generated', 'Roadmap generated'), ('roadmap_task_completed', 'Roadmap task completed'), ('essay_created', 'Essay created'), ('essay_review_requested', 'Essay review requested'), ('essay_review_completed', 'Essay review completed'), ('event_viewed', 'Event viewed'), ('event_registered', 'Event registered'), ('organizer_event_created', 'Organizer event created'), ('report_submitted', 'Report submitted'), ('demo_login_used', 'Demo login used'), ('notification_read', 'Notification read'), ('notification_archived', 'Notification archived'), ('admin_moderation_action', 'Admin moderation action')], db_index=True, max_length=60),
        ),
    ]
