# Generated by Django 5.2.15 on 2026-06-28 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import common.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event_service', '0003_alter_event_moderation_status_and_more'),
        ('university_service', '0003_university_admissions_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadmapPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=240)),
                ('cycle_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('target_country', models.CharField(blank=True, max_length=100)),
                ('primary_goal', models.CharField(blank=True, max_length=240)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('last_refreshed_at', models.DateTimeField(auto_now=True)),
                ('summary', models.TextField(blank=True)),
                ('readiness_snapshot', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-generated_at',),
            },
        ),
        migrations.CreateModel(
            name='RoadmapTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('profile', 'Profile'), ('exams', 'Exams'), ('essays', 'Essays'), ('universities', 'Universities'), ('scholarships', 'Scholarships'), ('activities', 'Activities'), ('research', 'Research'), ('portfolio', 'Portfolio'), ('deadlines', 'Deadlines'), ('events', 'Events'), ('recommendations', 'Recommendations')], db_index=True, max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='medium', max_length=10)),
                ('status', models.CharField(choices=[('todo', 'To do'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], db_index=True, default='todo', max_length=20)),
                ('due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('source_type', models.CharField(choices=[('generated', 'Generated'), ('manual', 'Manual'), ('university_deadline', 'University deadline'), ('profile_gap', 'Profile gap'), ('fit_analysis', 'Fit analysis'), ('essay_status', 'Essay status'), ('exam_plan', 'Exam plan'), ('event', 'Event')], default='generated', max_length=20)),
                ('linked_profile_section', models.CharField(blank=True, max_length=60)),
                ('generated_reason', models.TextField(blank=True)),
                ('evidence_note', models.TextField(blank=True)),
                ('source_url', models.URLField(blank=True, validators=[common.validators.validate_http_url])),
                ('dedup_key', models.CharField(blank=True, db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('linked_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roadmap_tasks', to='event_service.event')),
                ('linked_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roadmap_tasks', to='university_service.universityprogram')),
                ('linked_university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roadmap_tasks', to='university_service.university')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='roadmap_service.roadmapplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('due_date', '-priority', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='RoadmapTaskDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depends_on_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocking_for', to='roadmap_service.roadmaptask')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='roadmap_service.roadmaptask')),
            ],
        ),
        migrations.AddIndex(
            model_name='roadmaptask',
            index=models.Index(fields=['user', 'status'], name='roadmap_ser_user_id_cabfaa_idx'),
        ),
        migrations.AddIndex(
            model_name='roadmaptask',
            index=models.Index(fields=['plan', 'dedup_key'], name='roadmap_ser_plan_id_0abb11_idx'),
        ),
        migrations.AddConstraint(
            model_name='roadmaptaskdependency',
            constraint=models.UniqueConstraint(fields=('task', 'depends_on_task'), name='unique_roadmap_task_dependency'),
        ),
    ]
